### ISSUE TITLE
Push something

### ISSUE THREAD

**Issue by uday-sudo** [the-noob-coder69/dotmgr#1]
Pls push something in the repository, the Readme is so boring.

**Comment by hamburg1r** [comment]
Wait another 100 years

**Comment by uday-sudo** [comment]
Aalsi insaan kuch toh karle, bc jab dekho puchta hai kya karoon phir karta kuch nhi hai

**Comment by uday-sudo** [comment]
Wow such empty. Maybe atleast update the readme to explain the full purpose in some detail just so i can remember what this does and maybe i will suggest and help.

**Comment by uday-sudo** [comment]
Yo i ain't got no permission btw.
